image: node:latest
cache:
  paths:
    - node_modules/

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Installing dependencies..."
    - npm ci
    - echo "Dependencies installed."

unit-test-job:
  stage: test
  script:
    - echo "Installing vitest if not already installed..."
    - npm list vitest || npm install vitest
    - echo "Running tests with npm..."
    - npm run test
    - echo "Tests completed."
