image: node:latest
stages:          
  - build
  - test

build-job:       
  stage: build
  script:
    - echo "Installing dependencies..."
    - npm ci        
    - echo "Dependencies installed."

unit-test-job:   
  stage: test   
  script:
    - echo "Running tests with npm..."
    - npm run start   
    - echo "Tests completed."

